**27.** Выполнить обработку элементов прямоугольной матрицы 𝐴, имеющей 𝑛 строк и 𝑚 столбцов. Найти сумму элементов всей матрицы. Определить, какую долю в этой сумме составляет сумма элементов каждой строки. Результат оформить в виде матрицы из строк и столбцов.

In [34]:
import random
import numpy as np


def generate_matrix(n, m, a, b):
    return np.random.randint(a, b, size=(n, m))


matrix = generate_matrix(4, 3, 1, 5)
print(matrix)

[[3 4 2]
 [1 2 2]
 [2 2 3]
 [4 1 3]]


In [35]:
all_elements_sum = np.sum(matrix)
row_sums = np.sum(matrix, axis=1)

print("Общая сумма элементов:", elements_sum)
print("Сумма по каждой строке:", row_sums)

print("Результаты деления каждой суммы по строкам на общую сумму:")
for index, ratio in enumerate(row_sums / elements_sum):
    print(f"{index} строка занимает долю: {ratio:.3f}")

Общая сумма элементов: 33
Сумма по каждой строке: [9 5 7 8]
Результаты деления каждой суммы по строкам на общую сумму:
0 строка занимает долю: 0.273
1 строка занимает долю: 0.152
2 строка занимает долю: 0.212
3 строка занимает долю: 0.242
