**Первое задание:** Сгенерировать матрицу размером 6 × 5, заполненную целыми числами.

In [104]:
import random
import numpy as np


def generate_matrix(n, m, a, b):
    return np.random.randint(a, b, size=(n, m))


result_matrix = generate_matrix(6, 5, -41, 41)
print(result_matrix)

[[ 39  39 -30  -2  12]
 [ 19  38 -36 -25   6]
 [ 15 -14  17   3  37]
 [-17 -23  34  -4 -20]
 [-40 -19  14 -22  25]
 [-35 -14  10 -20  30]]


**Второе задание:** Вывести на экран элемент с индексами [4, 2].

In [105]:
print(result_matrix[4, 2])

14


**Третье задание:** Вывести на экран третью строку матрицы.

In [106]:
print(result_matrix[2])

[ 15 -14  17   3  37]


**Четвертое задание:** Вывести на экран четвертую строку матрицы в обратном порядке.

In [107]:
print(result_matrix[3][::-1])

[-20  -4  34 -23 -17]


**Пятое задание:** Изменить форму матрицы с 6 × 5 на 15 × 2.

In [108]:
print(result_matrix.reshape((15, 2)))

[[ 39  39]
 [-30  -2]
 [ 12  19]
 [ 38 -36]
 [-25   6]
 [ 15 -14]
 [ 17   3]
 [ 37 -17]
 [-23  34]
 [ -4 -20]
 [-40 -19]
 [ 14 -22]
 [ 25 -35]
 [-14  10]
 [-20  30]]


**Шестое задание:** Прибавить к каждому элементу матрицы заданное число.

In [109]:
number = 100
print(result_matrix + number)

[[139 139  70  98 112]
 [119 138  64  75 106]
 [115  86 117 103 137]
 [ 83  77 134  96  80]
 [ 60  81 114  78 125]
 [ 65  86 110  80 130]]


**Седьмое задание:** Найти максимум в каждой строке.

In [110]:
result_matrix

array([[ 39,  39, -30,  -2,  12],
       [ 19,  38, -36, -25,   6],
       [ 15, -14,  17,   3,  37],
       [-17, -23,  34,  -4, -20],
       [-40, -19,  14, -22,  25],
       [-35, -14,  10, -20,  30]])

In [111]:
print(np.max(result_matrix, axis=1))

[39 38 37 34 25 30]


**Восьмое задание:** Найти минимальный элемент в первом столбце.

In [112]:
# Выбирает все строки `:`, из первого стобца 
print(np.min(result_matrix[:, 0]))

-40


**Девятое задание:** Найти максимальный элемент в векторе 𝑥 среди элементов, перед которыми стоит нулевой.

In [122]:
# Подготовка данных
x = generate_matrix(10, 1, -41, 41)
x[1] = 0
x[5] = 0
x[7] = 0
x[8] = 0
x[9] = 0

zero_indices = np.where(x == 0)[0]
# Убираем индекс, если он 0 и является последним
zero_indices = zero_indices[zero_indices < len(x) - 1]
elements_after_zero = x[zero_indices + 1]

print(x)
print(np.max(elements_after_zero))

[[-10]
 [  0]
 [ 18]
 [-30]
 [-31]
 [  0]
 [  4]
 [  0]
 [  0]
 [  0]]
18


**Десятое задание:** Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.

In [123]:
matrix = generate_matrix(2, 4, -41, 41)
diagonal_elements = np.diagonal(matrix)
not_zero_diagonal_elements = diagonal_elements[diagonal_elements != 0]

print("matrix:")
print(matrix)
print("diagonal_elements:", diagonal_elements)
print("Произведение:", np.prod(not_zero_diagonal_elements))

matrix:
[[-25 -19  28  22]
 [ 27  29  -9 -20]]
diagonal_elements: [-25  29]
Произведение: -725
