**27.** Дан вектор 𝑥 и матрица 𝐴. Умножить каждый четный столбец матрицы 𝐴 на вектор 𝑥. Результат записать в новую матрицу и умножить ее на второй элемент вектора х.

In [157]:
import random
import numpy as np


def generate_matrix(n, m, a, b):
    return np.random.randint(a, b, size=(n, m))


matrix = generate_matrix(3, 6, 1, 5)
x = generate_matrix(3, 1, 1, 5)
print(x)
print(matrix)

[[3]
 [4]
 [3]]
[[4 1 1 1 3 3]
 [1 4 1 3 2 3]
 [2 1 3 2 1 2]]


In [158]:
new_matrix = matrix 
new_matrix[::, 1::2] = matrix[::, 1::2] * x
new_matrix * x[1]

array([[16, 12,  4, 12, 12, 36],
       [ 4, 64,  4, 48,  8, 48],
       [ 8, 12, 12, 24,  4, 24]])